<html>
<head>
     <meta charset="utf-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="icon" href="./assets/favicon.jpg">
     <title>PeelPages</title>
         <link href="./css/bootstrap.min.css" rel="stylesheet">
         <link rel="stylesheet" href="css/styles.css"> 
         <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
         <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
         <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
         <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
	<!--Import model-->
	<div class="container" style="margin-left: 30%;margin-top: 5%;">
	<div style="position:relative;">
		<!--Model content-->
		<form action="import.php" method="POST" id="importform" style="margin-top: 2%;" enctype="multipart/form-data">
			<a href="#" class="btn btn-success" style="margin-bottom: 15px;">Please Click to open a .tsv file and type a name for a new address book, then click save!</a>
			<div>
				<input type="text" value="" style="float: left;" name="aname" required>
				<input type='file' style="opacity:0;filter:alpha(opactiy=0);position:absolute;top:0;left:0;width:584px;height:34px;cursor:pointer;" id = "input" name = "input" style="float: left; margin-left: 25px;">
				<input class="btn btn-success" type="submit" value="Save" style="float: left; margin-left: 25px;" >
			</div>
		</form>
	</div>
	</div>
</body>

<?php
	include('connectionData.txt');
	$aname = $_POST['aname'];
	// Check the file is readed successful and a name is typed
	if ($_FILES["input"]["error"] <= 0 && $aname != '')
	{	
		// Conect to database
		$con = mysqli_connect($server, $user, $pass, $dbname, $port);
		// Get the typed name
		$addressname = $_POST['aname'];
		// MySql query to insert an address into database
		$sql = "insert into address(add_name, add_date) values('".$addressname."', sysdate())";
		// Excute MySql query
		mysqli_query($con, $sql);
		// Get the ID generated by a query on a table with a column having the AUTO_INCREMENT attribute
		$addId = mysqli_insert_id($con);		
		// Get the current time, it is used for temporary file's name
		$d = date('YmdHis',time());
		// Create the temporary file's name
		$filename = $d.".tsv";
		// Copy the cache file to a local folder
		move_uploaded_file($_FILES["input"]["tmp_name"], "upload/".$filename);
		// Open the tsv file
		$file = fopen("upload/".$filename, "r");
		// Create an array to store the tsv file's content
		$user=array();
		// Store the row's number
		$i=0;
		// Read every row from the tsv file until the last
		while(!feof($file))
		{	
			// Create array for each row
			$user[$i]= fgets($file);
			// Use /t to split every entry in one row
			$users = explode('	', $user[$i]);
			// Don't insert the first row
			if (0 != $i && count($users) == 8)
			{
				// MySql query to insert a contact into database
				$sql = "insert into contact(fName,lName,address1,address2,phone_num,city,state,zip,addre_id) values('$users[6]','$users[5]','$users[3]','$users[4]','$users[7]','$users[0]','$users[1]','$users[2]',$addId)";
				// Excute MySql query
				mysqli_query($con, $sql);
			}
			$i++;
		}
		// Close the file
		fclose($file);
		// Hint the user import successful
		echo"<script language=javascript>alert('Import Successful!');</script>";
	}
	// Catch the exception
	if($_FILES["input"]["error"] > 0)
	{
		// Hint the user import failed
		echo"<script language=javascript>alert('Please choose a .tsv file!');</script>";
	}

?>

</html>





